spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-db.carsvdpnndtv.ap-northeast-2.rds.amazonaws.com:3306/Board
    username: root
    password: akwldrk1
  security:
    user:
      name: user1
      password: 123123

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/html/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/com/example/mybatisStore/user/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.mybatisStore.user

server:
  port: 8060

springdoc:
  version: 2.0.2

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

logging:
  level:
    org.springframework.security: DEBUG
