spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-db.carsvdpnndtv.ap-northeast-2.rds.amazonaws.com:3306/Board
    username: root
    password: akwldrk1
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: master
      password: 1234
      roles: ADMIN
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:mapper/com/example/mybatisStore/user/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.mybatisStore.user

server:
  port: 8060

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
